### ISSUE TITLE
Remove FL_THIRDPARTYBOT flag completely

### ISSUE THREAD

**Issue by jeefo** [RGreenlees/evobot_mm#3]
Hi!

This flag was used bot-coders in early days of steam release of CS 1.6, as official cs-bots crashed games on entities wearing normal FL_FAKECLIENT flag.

So it's should be replaced with FL_FAKECLIENT.

**Comment by EterniumDev** [comment]
Actually the THIRDPARTYBOT flag is useful for the Commander role to determine a human comm vs an bot commander since FAKECLIENT flag cannot be used on a bot commander

**Comment by RGreenlees** [comment]
Thanks Jeefo! I have removed FL_THIRDPARTYBOT, and I also remove FL_FAKECLIENT for the AI commander and it seems to work ok with no side-effects. As @EterniumDev suggests, if we run into problems I'll try re-applying the THIRDPARTYBOT flag just for commander.
